### ISSUE TITLE
Can't load it's own Pattern Load Cues (Sonic 1 format)

### ISSUE THREAD

**Issue by SameytheHedgehog** [Clownacy/clownmaped#2]
When trying to re-open PLCs you've exported, CME says that they're "incompatible with the currently mappings" even if they're the exact same mappings you exported the PLCs with.

It can load any PLCs exported by SonMapEd however.

How to reproduce:
1. Load mappings (e.g. Sonic's after being fixed so CME won't refuse to load it [just add Map_Sonic: to the beginning of the mappings])
2. Load Sonic's PLCs
3. Save the PLCs
4. try loading the newly saved PLCs

I've also noticed that the PLCs that CME exports seem to be broken when loading them into SonMapEd, just making the mappings appear to be a garbled mess, especially for complex mappings that reference tiles all over the art file.

Default Sonic 1 (Old Hivebrain ASM68k) can't seem to load them properly either, as seemingly random frames will bug out and have the wrong tiles loaded.

**Comment by SameytheHedgehog** [comment]
Random side-note:
CME can't seem to be able to load the original Sonic PLCs that come with the old Hivebrain asm68k disassembly, simply saying "file could not be assembled" when I try to load it.

**Comment by Clownacy** [comment]
Sonic's PLCs have the same issues as his mappings: they're missing the label at the start. Adding that gets the file to load successfully.

The reason that the exported PLCs cannot be loaded successfully is because you're trying to combine them with the original mappings: mappings and PLCs are 'paired' together, so trying to use mappings from one pair with PLCs from another pair will not work. You need to export both the mappings and the PLCs, and then you can load them.

**Comment by SameytheHedgehog** [comment]
Ah I see now, I didn't think about the mappings and dplcs being paired up like this.
After exporting both mappings and dplcs and building, it works perfectly fine. :)

SME would just let me load them in whichever way I wanted. That'll have to be something I just have to get used to I suppose.

I also suppose this one was just user-error for the most part so I'll just close this one as otherwise it'll mostly be a duplicate of the other issue.
